### ISSUE TITLE
Links to documentation in README go to pages that don't exist

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDatabases/SQLite.jl#135]
Neither of
- https://juliadb.github.io/SQLite.jl/stable
- https://juliadb.github.io/SQLite.jl/latest

exists.

Additionally, you may consider removing the "Documentation" `<h2>` altogether since the same pages are referenced in the README's badges.

**Comment by aviks** [comment]
Should be fixed now. Thanks for the reminder.

**Comment by non-Jedi** [comment]
@aviks Links to documentation on http://juliadatabases.github.io/SQLite.jl/ (which appears to just be a formatted version of an out-of-date README?) are still broken.
